var manifest = [
	{src:"./res/screen_sex_0_btn_0.dat?1818", id:"screen_sex_0_btn_0", type:"text"},
	{src:"./res/screen_sex_0_btn_1.dat?1818", id:"screen_sex_0_btn_1", type:"text"},
	{src:"./res/screen_sex_0_btn_2.dat?1818", id:"screen_sex_0_btn_2", type:"text"},
	{src:"./res/screen_sex_0_btn_3.dat?1818", id:"screen_sex_0_btn_3", type:"text"},
	{src:"./res/screen_sex_0_btn_cum.dat?1818", id:"screen_sex_0_btn_cum", type:"text"},
	{src:"./res/screen_sex_0_btn_cum_.dat?1818", id:"screen_sex_0_btn_cum_", type:"text"},
	{src:"./res/screen_sex_1_btn_0.dat?1818", id:"screen_sex_1_btn_0", type:"text"},
	{src:"./res/screen_sex_1_btn_1.dat?1818", id:"screen_sex_1_btn_1", type:"text"},
	{src:"./res/screen_sex_1_btn_2.dat?1818", id:"screen_sex_1_btn_2", type:"text"},
	{src:"./res/screen_sex_1_btn_3.dat?1818", id:"screen_sex_1_btn_3", type:"text"},
	{src:"./res/screen_sex_1_btn_cum.dat?1818", id:"screen_sex_1_btn_cum", type:"text"},
	{src:"./res/screen_sex_1_btn_cum_.dat?1818", id:"screen_sex_1_btn_cum_", type:"text"},
	{src:"./res/screen_sex_2_btn_0.dat?1818", id:"screen_sex_2_btn_0", type:"text"},
	{src:"./res/screen_sex_2_btn_1.dat?1818", id:"screen_sex_2_btn_1", type:"text"},
	{src:"./res/screen_sex_2_btn_2.dat?1818", id:"screen_sex_2_btn_2", type:"text"},
	{src:"./res/screen_sex_2_btn_3.dat?1818", id:"screen_sex_2_btn_3", type:"text"},
	{src:"./res/screen_sex_2_btn_cum.dat?1818", id:"screen_sex_2_btn_cum", type:"text"},
	{src:"./res/screen_sex_2_btn_cum_.dat?1818", id:"screen_sex_2_btn_cum_", type:"text"}
];